# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
email: dev.vitor.navarro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Vitor navarro and this is my corner in the web, </br> if you're here for any of my posts, projects or to know
  more about me, this is the right place.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vnavarro.com.br"
twitter_username: vitor_navarro
github_username:  vnavarro
logo: "/assets/avatar.png"

# Build settings
#theme: minima
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-compose
  #- jekyll-polyglot

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:

#polyglot config
#languages: ["en", "pt"]
#default_lang: "pt"
#exclude_from_localization: ["assets", "javascript", "images", "css", "public"]
#parallel_localization: true

skin: "/assets/css/skins/myskin.css"

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

#paginate: 10  # amount of posts to show per page
#paginate_path: /page:num/

# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 5
#   offset: 0
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
# # Produces a cleaner folder structure when using categories
# permalink: /:year/:month/:title.html

sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  title: "Vitor Navarro's site"
  description: "This is my personal site where I share posts about my projects, programming, technology and a bit more."
  author: "Vitor Navarro"
  excerpt_only: true