lang_name: Português 🇧🇷
description: >-
  Oi, seja bem vinda(o)! Sou Vitor Navarro e este é meu cantinho 
  na web, </br>aqui você encontra um pouco do meu trabalho, meus artigos,
  projetos e informações sobre mim. </br>Todos meus outros links estão na 
  página Sobre.
highlights: Destaques
top-recomendations-by-me: Minhas recomendações
top-recomendations-by-me-content: >-
  <p>Estes são produtos que eu uso ou usei no passado, eu acredito e confio nas suas qualidades e performance e acredito que merecem atenção de outras pessoas.</p>
  <p>Assine os serviços do Surfshark através do meu link e consiga 3 meses grátis.<br>Permaneça por 31 dias e eu ganho um presente de volta.<br><a href="https://surfshark.club/friend/JL7FnC6D" target="_blank">Dê uma olhada</a> <a href="https://surfshark.club/friend/JL7FnC6D" target="_blank">
      <img src="/assets/img/SVG/Surshark_Logo_White.svg" alt="Surfshark Logo" width="100px">
  </a>
  </p>
  <p>Assine o Husky para receber pagamentos do mundo inteiro por uma pequena taxa.<br> Você recebe seu primeiro pagamento sem taxa e +3 coupons de 50% de desconto nos próximos pagamentos com meu link.<br><a href="https://husky.io?ref=oge4otq" target="_blank">Dê uma olhada</a> <a href="https://husky.io?ref=oge4otq" target="_blank">
      <img src="/assets/img/huskynomad-dark-pb-flat.png" alt="Husky Logo" max-height="24px" width="100px">
  </a></p>
latest-posts: Posts mais recentes
more: mais
posts-disclaimer: Alguns posts só existem em inglês outros só em português, ainda estou normalizando as traduções.
back_to_top: Para o topo