// Only one item MUST have the "default: true" key

module.exports = {
  en: {    
    default: true,
    path: `en`,
    locale: `en-US`,
    dateFormat: `DD/MM/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `Welcome to my portfolio`,
    defaultDescription: `Here you find mutiple content both about me and generated by me.`,
  },
  pt: {    
    path: `pt`,
    locale: `pt-BR`,
    dateFormat: `DD/MM/YYYY`,
    siteLanguage: `pt`,
    ogLanguage: `pt_BR`,
    defaultTitle: `Bem vindo ao meu portfólio`,
    defaultDescription: `Aqui você encontra conteúdo sobre mim e gerado por mim.`,
  },
}
