lang_name: English 🇨🇦
description: >-
  Hi, welcome! I'm Vitor Navarro and this is my corner in the web, 
  </br>here you will find a bit of my job, my articles, projects and 
  information about me. </br>You can get all my other links in the 
  About page.
highlights: Highlights
top-recomendations-by-me: Top recommendations by me
top-recomendations-by-me-content: >-
  <p>These are products that I use or have used in the past, that I trust and believe to have quality and performance deserving the attention of others.</p>
  <p>Subscribe to Surfshark services via my friend link and get up to 3 free months.<br>Stays for 31 days and I get some gift back.<br><a href="https://surfshark.club/friend/JL7FnC6D" target="_blank">Check it out</a> <a href="https://surfshark.club/friend/JL7FnC6D" target="_blank">
      <img src="/assets/img/SVG/Surshark_Logo_White.svg" alt="Surfshark Logo" width="100px">
  </a>
  </p>
  <p>Subscribe to Husky and receive payments from all over the world with the smallest tax.<br> You receive first payment without tax and +3 coupons of 50% off for next payments with my link.<br><a href="https://husky.io?ref=oge4otq" target="_blank">Check it out</a> <a href="https://husky.io?ref=oge4otq" target="_blank">
      <img src="/assets/img/huskynomad-dark-pb-flat.png" alt="Husky Logo" max-height="24px" width="100px">
  </a></p>
latest-posts: Latest posts
more: more
posts-disclaimer: Some posts only exist in english others only on portuguese, I'm still standardizing translations.
back_to_top: Back to top